apiVersion: v1
kind: PersistentVolume
metadata:
  name: voltest
spec:
  storageClassName: "expansion"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  gcePersistentDisk:
    pdName: voltest
    fsType: ext4

#
#
# gcloud compute disks create --size=20GB --zone=us-central1-a voltest
#
#
