apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voltest
spec:
  volumeName: voltest
  storageClassName: "expansion"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi